name: Mailing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Chekcout repository
        uses: actions/checkout@v3
        
      - name: Build service
        run: docker-compose up -d
      
  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Pytest executing
        run: docker-compose exec -it mailer pytest
